server:
  port: 8086

spring:
  application:
    name: stage07-error-handling

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: stage07-group
      auto-offset-reset: earliest
      enable-auto-commit: false

logging:
  level:
    com.kafka.stage07: DEBUG
    org.springframework.kafka: INFO
